import { test, expect } from "@playwright/test";
import { signIn } from "./helpers";

test.describe("payments (dev-mock provider)", () => {
  test("one-time report: consent required, mock pay, generation completes", async ({ page }) => {
    await page.goto("/en/order/tarot-deep-reading");
    await page.getByRole("radio", { name: /career/i }).click();

    // Consent gate (§7.8): attempting to pay without consent shows an error.
    await page.getByRole("button", { name: /continue to secure payment/i }).click();
    await expect(page.getByText(/immediate-delivery consent|tick the/i)).toBeVisible();

    await page.getByLabel(/i agree to immediate delivery/i).check();
    await page.getByRole("button", { name: /continue to secure payment/i }).click();

    // Dev-mode report page: order is payment_pending until simulated webhook.
    await page.waitForURL(/\/en\/reports\//, { timeout: 20_000 });
    await expect(page.getByText(/awaiting payment/i)).toBeVisible();
    await page.getByRole("button", { name: /simulate payment/i }).click();

    // Redirect alone never marks paid — fulfillment drives the status.
    await expect(page.getByText(/completed/i).first()).toBeVisible({ timeout: 45_000 });
    await expect(page.getByRole("main").getByRole("img")).toHaveCount(10); // 10 drawn cards render
    await expect(page.getByText(/generated by AI from structured reading data/i).first()).toBeVisible();
  });

  test("subscription: subscribe (mock), cancel online, resume", async ({ page }) => {
    const email = `e2e-sub-${Date.now()}@test.local`;
    await signIn(page, email);

    await page.goto("/en/pricing");
    await page.getByRole("button", { name: /subscribe monthly/i }).click();
    await page.waitForURL(/account\/subscription/, { timeout: 20_000 });
    await expect(page.getByText(/active/i).first()).toBeVisible();

    // Direct online cancellation — no dark patterns (spec §15).
    await page.getByRole("button", { name: /cancel subscription/i }).click();
    await page.getByRole("button", { name: /^confirm$/i }).click();
    await expect(page.getByText(/will end on/i)).toBeVisible({ timeout: 15_000 });

    await page.getByRole("button", { name: /resume subscription/i }).click();
    await expect(page.getByText(/next renewal/i)).toBeVisible({ timeout: 15_000 });
  });
});
