import { test, expect } from "@playwright/test";

test.describe("guest tarot flow", () => {
  test("daily card: draw, reveal, interpretation with disclosure @mobile", async ({ page }) => {
    await page.goto("/en/tarot/daily");
    await page.getByRole("button", { name: /shuffle/i }).click();
    await page.getByRole("button", { name: /reveal/i }).click();
    // Deterministic card facts render immediately…
    await expect(page.getByRole("img", { name: /\((upright|reversed)\)$/i }).first()).toBeVisible();
    // …and the interpretation (mock in dev) follows with limitations + AI disclosure.
    await expect(page.getByText(/sample interpretation|interpretation/i).first()).toBeVisible({ timeout: 30_000 });
    await expect(page.getByText(/generated by AI from structured reading data/i)).toBeVisible();
  });

  test("one-card flow collects topic and question, then interprets", async ({ page }) => {
    await page.goto("/en/tarot/one-card");
    await page.getByRole("radio", { name: /personal growth/i }).click();
    await page.getByLabel(/your question/i).fill("How should I approach the change I'm considering?");
    await page.getByRole("button", { name: "Next", exact: true }).click();
    await expect(page.getByText(/take one slow breath/i)).toBeVisible();
    await page.getByRole("button", { name: /shuffle/i }).click();
    await page.getByRole("button", { name: /reveal/i }).click();
    await expect(page.getByRole("heading", { name: /a question to sit with/i })).toBeVisible({ timeout: 30_000 });
  });

  test("crisis question is blocked with support resources and no reading", async ({ page }) => {
    await page.goto("/en/tarot/one-card");
    await page.getByLabel(/your question/i).fill("I want to end my life, what do the cards say?");
    await page.getByRole("button", { name: "Next", exact: true }).click();
    await page.getByRole("button", { name: /shuffle/i }).click();
    await expect(page.getByText(/988|emergency services/i)).toBeVisible({ timeout: 15_000 });
    await expect(page.getByRole("button", { name: /reveal/i })).toHaveCount(0);
  });

  test("zh locale renders the tarot flow in Chinese", async ({ page }) => {
    await page.goto("/zh/tarot/daily");
    await expect(page.getByRole("button", { name: "洗牌抽取" })).toBeVisible();
    await page.getByRole("button", { name: "洗牌抽取" }).click();
    await expect(page.getByRole("button", { name: "翻开" })).toBeVisible({ timeout: 15_000 });
  });
});
